LIST_ONE = []
LIST_TWO = []

LIST_ONE = input().split(' ')
LIST_TWO = input().split(' ')

PART_CODE_ONE = int(LIST_ONE[0])
PART_NUMBER_ONE = int(LIST_ONE[1])
UNIT_VALUE_PART_ONE = float(LIST_ONE[2])
PART_CODE_TWO = int(LIST_TWO[0])
PART_NUMBER_TWO = int(LIST_TWO[1])
UNIT_VALUE_PART_TWO = float(LIST_TWO[2])

TOTAL = ((PART_NUMBER_ONE * UNIT_VALUE_PART_ONE) + (PART_NUMBER_TWO * UNIT_VALUE_PART_TWO))

print('VALOR A PAGAR: R$ %0.2f'%TOTAL)